### ISSUE TITLE
有个比较明显的问题

### ISSUE THREAD

**Issue by kakugg** [ljd1996/BgStarter#1]
你的demo是将当前的activity移动到后台，用的movetasktoBack的，然后每次几乎只需要重新移动到前台，然后正常的就吊起来了，但是如果按了home键，就凉凉了，这个有什么办法可以搞定吗？

**Comment by ljd1996** [comment]
@kakugg 我在Android 9的小米Max3上测试的结果是应用正常退到后台(点击home)，然后也是可以从后台启动的。你这边凉凉的原因可能是因为机型？至于使用movetasktoBack只是用来模拟退到后台的动作

**Comment by kaiduo** [comment]
Android10 点击HOME 凉凉   movetasktoBack后移动前台时间改成10秒 凉凉
