### ISSUE TITLE
oppo上不行哎

### ISSUE THREAD

**Issue by EdisonLiao** [ljd1996/BgStarter#2]
我改了一下demo，设置监听锁屏，但是在oppo上好像不能后台弹出

**Comment by ljd1996** [comment]
是在锁屏状态下吗？锁屏的话可能还有其它权限，小米是有锁屏显示权限的，OPPO不确定有没有

> 我改了一下demo，设置监听锁屏，但是在oppo上好像不能后台弹出

**Comment by EdisonLiao** [comment]
嗯嗯，oppo上有锁屏页的适配问题
